--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/SVega9848/VegaHCFElevator
build-by-default: true
branches:
- main
projects:
  VegaHCFElevator:
    path: ""
    icon: "logo.png"
...
